# Generated by Django 3.2.5 on 2021-07-11 21:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Excercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ExcerciseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magnitude', models.DecimalField(decimal_places=2, max_digits=8)),
                ('repetitions', models.PositiveIntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('D', 'distance'), ('R', 'repetitions')], default='R', max_length=1)),
                ('unit', models.CharField(choices=[('K', 'kg'), ('L', 'lb'), ('M', 'm'), ('N', '')], default='N', max_length=1)),
                ('excercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crossfit.excercise')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('A', 'AMRAP'), ('T', 'for time'), ('M', 'max')], default='T', max_length=1)),
                ('excercises', models.ManyToManyField(to='crossfit.ExcerciseDetails')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('excercises', models.ManyToManyField(to='crossfit.ExcerciseDetails')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crossfit.workout')),
            ],
        ),
    ]
