# Generated by Django 3.2.5 on 2021-07-11 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('G', 'gym'), ('A', 'area')], default='A', max_length=1)),
            ],
        ),
    ]
